---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Вынести категории отдельным списком ( на подобии списка производителей )
  - Списки товаров должны быть на предаставленных языках
  - Сделать отдельную страницу под разные категории товаров ( Не должны быть все творы одним списком )
  - Добавить личный кабинет пользователя
  - Добавить возможность при добавлении товара в корзину выбрать количество тавара
